name: CI

on:
  push: {}

permissions:
  contents: read

concurrency: # Avoid needlessly continuing the workflow when there's a newer commit
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: 'false'

      - name: cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        run: cargo test --verbose

      - name: fmt
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy -- -Dwarnings

      - name: build
        run: cargo build --verbose

      - name: docker
        run: docker build .

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          advanced-security: 'false'
          persona: auditor
          annotations: 'true'
