name: CI

on:
  push: {}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        run: cargo test --verbose

      - name: fmt
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy -- -Dwarnings

      - name: build
        run: cargo build --verbose

      - name: docker
        run: docker build .
